print("Suma y resta:")
print(2 + 2)
print(-4 + 4)
print(-4. + 8)
print(2 - 2)
print(-4 - 4)
print(4. - 8)
print()

print("Operador unario de signo:")
print(+1.1)
print(-1.1)
print()

print("Multiplicacion:")
print(2 * 3)
print(2 * 3.)
print(2. * 3)
print(2. * 3.)
print()

print("Exponenciacion:")
print(2 ** 3)
print(2 ** 3.)
print(2. ** 3)
print(2. ** 3.)
print()

print("Division:")
print("- NOTA: El resultado de la division en Python siempre es flotante.")
print(6 / 3)
print(6 / 3.)
print(6. / 3)
print(6. / 3.)
print()

print("Division Entera (floor division):")
print(6 // 3)
print(6 // 3.)
print(6. // 3)
print(6. // 3.)
print()

print("Division Entera vs Division Normal:")
print("- NOTA: La division entera siempre redondea el valor hacia abajo.")
print(6 // 4)
print(6. // 4)
print(6 / 4)
print(6. / 4)
print(-6 // 4)
print(6. // -4)
print(-6 / 4)
print(6. / -4)
print()

print("Modulo:")
print(14 % 4)
print(12 % 4.5)
print("12 // 4.5 = 2.0")
print("2.0 * 4.5 = 9.0")
print("12 - 9.0 = 3.0")
print()

# Division entre cero:
# - Dividir entre cero.
# print(12 / 0)
# - Realizar una división entera entre cero.
# print(12 // 0)
# - Encontrar el residuo de una división entre cero.
# print(14 % 0)
